name: CI

on:

  # Trigger on push to any branch
  push:

  # Trigger on manual dispatch
  workflow_dispatch:

  # Trigger twice a month at 6:00 a.m.
  schedule:
    - cron:  '0 6 */14 * *'

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            install: |
                sudo apt-get update
                sudo apt install -y zsh vim git curl universal-ctags
          - os: macos-latest
            install: |
                brew install zsh vim curl universal-ctags

    steps:

    - name: Install dependencies
      run: ${{ matrix.install }}

    - name: Build dotfiles
      run: |
        curl -Ls https://gist.github.com/dhnza/6b384f52ce32342761cc00f9d26311fa/raw/dotfiles-init.sh | /bin/bash
        #TODO: add branch to script??
        git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout ${GITHUB_REF##*/}
        $HOME/.dotfiles-install.sh

    - name: Check installation
      shell: zsh {0}
      run: |
        set -e
        # Check zsh plugins
        #TODO: work around for zplug's pipe incompatibility
        zsh <<< "source $HOME/.zshrc; zplug check --verbose"
        # Check cargo packages
        command -v cargo
        command -v fd
        command -v rg
        command -v bat
        # Check vim plugins
        vim +PlugStatus +"write temp" +qall <<< '\n' > /dev/null
        [[ 0 == $(awk '/Finished./ {print $2}' temp) ]]
        rm -f temp
